# Generated by Django 4.1.1 on 2022-09-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='type',
            field=models.CharField(choices=[('1', 'aaa'), ('2', 'bbb')], default='hej', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='window',
            name='direction_of_opening',
            field=models.CharField(choices=[('1', 'to the inside'), ('2', 'to the outside')], max_length=100),
        ),
    ]
