# Generated by Django 4.1.1 on 2022-09-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_window_type_alter_window_direction_of_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='type',
            field=models.CharField(choices=[('1', 'obenable - type 1'), ('2', 'openable - type 2'), ('3', 'openable - tyle 3'), ('4', 'unopenable')], max_length=100),
        ),
    ]
