# Generated by Django 4.1.1 on 2022-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_window_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='direction_of_opening',
            field=models.CharField(choices=[('1', 'to the inside'), ('2', 'to the outside'), ('3', 'unopenable')], max_length=100),
        ),
    ]
