# Generated by Django 4.1.1 on 2022-09-18 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_window_direction_of_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='direction_of_opening',
            field=models.CharField(choices=[('1', 'to the inside'), ('2', 'to the outside'), ('3', 'unopenable')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='window',
            name='height',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(2500)]),
        ),
        migrations.AlterField(
            model_name='window',
            name='type',
            field=models.CharField(choices=[('1', 'obenable - type 1'), ('2', 'openable - type 2'), ('3', 'openable - tyle 3'), ('4', 'unopenable')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='window',
            name='width',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(2500)]),
        ),
    ]
