# Generated by Django 4.1.1 on 2022-09-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_window_direction_of_opening_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotation',
            new_name='Offer',
        ),
        migrations.AddField(
            model_name='window',
            name='acoustics',
            field=models.CharField(choices=[('standard_acoustics', 'standard'), ('super_acoustics', 'super')], default='standard_acoustics', max_length=20),
        ),
        migrations.AddField(
            model_name='window',
            name='additional_options',
            field=models.CharField(choices=[('additional_vent', 'additional vent'), ('security_lock', 'security lock in the handle'), ('rc2', 'fittings with increased resistance to burglary (RC2)')], default='rc2', max_length=20),
        ),
        migrations.AddField(
            model_name='window',
            name='thermics',
            field=models.CharField(choices=[('standard_thermics', 'standard'), ('super_thermics', 'super')], default='standard_thermics', max_length=20),
        ),
        migrations.AlterField(
            model_name='window',
            name='direction_of_opening',
            field=models.CharField(choices=[('to_the_inside', 'to the inside'), ('to_the_outside', 'to the outside'), ('unopenable', 'unopenable')], default='to_the_inside', max_length=20),
        ),
        migrations.AlterField(
            model_name='window',
            name='type',
            field=models.CharField(choices=[('openable_type1', 'obenable - type 1'), ('openable_type2', 'openable - type 2'), ('openable_type3', 'openable - tyle 3'), ('unopenable', 'unopenable')], default='openable_type1', max_length=20),
        ),
    ]
