# Generated by Django 4.1.1 on 2022-09-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_rename_quotation_offer_window_acoustics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='additional_options',
            field=models.CharField(choices=[('additional_vent', 'additional vent'), ('security_lock', 'security lock in the handle'), ('rc2', 'fittings with increased resistance to burglary (RC2)')], default='additional_vent', max_length=20),
        ),
    ]
